evaluation_cfg:
  metrics:
    - AccessibilityMetric
  output_dir: ./output_eval_test
  skip_completed: True
  save_blend_file: False
  save_trimesh_glb: True
  vlm: GPT
  use_existing_matching: False
  use_empty_matching_result: True
  support_metric_use_existing_support_type_assessment: False
  no_eval: False
  verbose: False

input_cfg:
  root_dir: ./input
  scene_methods:
    - IDesign
  method_use_simple_architecture: []
  scene_mode: list
  scene_range: [0, 1]
  scene_list: [3]
  annotation_file: /home/ubuntu/efs/nicholas/scene-agent-eval-scenes/annotations.csv

render_cfg:
  normal_render_tasks: []
  semantic_render_tasks: null
  semantic_color_reference: null
  export_web_glb: false
  web_glb_max_texture_size: 512
  hdri_path: null
